### ISSUE TITLE
[Guide] for Tandoor

### ISSUE THREAD

**Issue by schwantuschke** [Uberspace/lab#1134]
Please write a Guide for [Tandor](https://tandoor.dev/). Thanks :)

**Comment by schwantuschke** [comment]
I try this installation with this [manual](https://docs.tandoor.dev/install/manual/). I get an error at step _Install project requirements_ with `yarn build`:

> $ yarn build
yarn run v1.22.15
$ vue-cli-service build
> ⠙  Building for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
⠴  Building for production...events.js:291
      throw er; // Unhandled 'error' event
      ^
> Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:456:14)
    at PoolWorker.writeJson (/var/www/virtual/eml/recipes/vue/node_modules/thread-loader/dist/WorkerPool.js:122:20)
    at PoolWorker.run (/var/www/virtual/eml/recipes/vue/node_modules/thread-loader/dist/WorkerPool.js:104:10)
    at WorkerPool.distributeJob (/var/www/virtual/eml/recipes/vue/node_modules/thread-loader/dist/WorkerPool.js:332:18)
    at runQueue (/var/www/virtual/eml/recipes/vue/node_modules/neo-async/async.js:8099:9)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EPIPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Can anyone help me?

**Comment by knhash** [comment]
@schwantuschke, I faced the same issue when I skipped the error of `microdata` not installing in a previos step (did you, too, skip ahead anyway?):
```
ERROR: Could not find a version that satisfies the requirement microdata==0.7.1 (from versions: 0.1, 0.2, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1, 0.7.0, 0.7.1)
ERROR: No matching distribution found for microdata==0.7.1
```

(side note, the error is a little misleading, 0.7.1 is right there in one of the options...)

Modifying the requirements file to install `microdata==0.4.0` instead, then trying `yarn build` succeeded for me. Try that please.

**Comment by schwantuschke** [comment]
I edit requirements.txt and executed `bin/pip3.9 install -r requirements.txt`.
`yarn install` works fine. But with `yarn build` I get the same error as above :(

I didn't have the problem with microdata.

**Comment by leitwolf7** [comment]
So is there now a working way to get Tandoor working on uberspace? @knhash your coment sounds like you have it up and running?

**Comment by knhash** [comment]
Hey @leitwolf7 , it has been a while but I am afraid I am not able to replicate an install now. I run into out of memory while running `yarn build`.
