### ISSUE TITLE
[friendica] guide is broken

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1254]
The guide for [friendica] does not work anymore. 

```
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "[02-May-2022 17:16:51 Europe/Berlin] PHP Notice:  Undefined index: Psr\Log\NullLogger in /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php on line 134"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "[02-May-2022 17:16:51 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Friendica\Database\Database::__construct() must implement interface PsrExt\Log\LoggerInterface, instance of Friendica\Core\Logger\Factory\Logger given in /var/www/virtual/isabell/html/src/Database/Database.php:76"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "Stack trace:"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#0 [internal function]: Friendica\Database\Database->__construct(Object(Friendica\Core\Config\ValueObject\Cache), Object(Friendica\Util\Profiler), Object(Friendica\Core\Logger\Factory\Logger))"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#1 /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs(Object(Friendica\Database\Database), Array)"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#2 /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}(Array, Array)"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#3 /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php(247): Dice\Dice->create('Friendica\\Datab...', Array, Array)"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#4 /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php(149): Dice\Dice->Dice\{closure}(Array, Array)"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#5 /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php(96): Dice\Dice->D in /var/www/virtual/isabell/html/src/Database/Database.php on line 76"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "[02-May-2022 17:16:51 Europe/Berlin] PHP Notice:  Undefined index: Psr\Log\NullLogger in /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php on line 134"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "[02-May-2022 17:16:51 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Friendica\Database\Database::__construct() must implement interface PsrExt\Log\LoggerInterface, instance of Friendica\Core\Logger\Factory\Logger given in /var/www/virtual/isabell/html/src/Database/Database.php:76"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "Stack trace:"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#0 [internal function]: Friendica\Database\Database->__construct(Object(Friendica\Core\Config\ValueObject\Cache), Object(Friendica\Util\Profiler), Object(Friendica\Core\Logger\Factory\Logger))"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#1 /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs(Object(Friendica\Database\Database), Array)"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#2 /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}(Array, Array)"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#3 /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php(247): Dice\Dice->create('Friendica\\Datab...', Array, Array)"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#4 /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php(149): Dice\Dice->Dice\{closure}(Array, Array)"
[02-May-2022 17:16:51] WARNING: [pool www] child 18983 said into stderr: "#5 /var/www/virtual/isabell/html/vendor/level-2/dice/Dice.php(96): Dice\Dice->D in /var/www/virtual/isabell/html/src/Database/Database.php on line 76"
```

We added a banner to the guide to signal the broken state.

If you have any insights, please comment on this issue. Pull requests fixing the guide are also highly appreciated. If the guide does not get fixed within two months, we will remove it from the lab, as documented in the [broken guides policy](https://github.com/Uberspace/lab/blob/main/BROKEN_GUIDES.md).

@toddy15  FYI.

**Comment by toddy15** [comment]
@noave Thanks for notifying me.

This seems to be a relatively new problem: https://github.com/friendica/friendica/issues/11216#issuecomment-1114967771

I assume that there's a problem with friendica itself, not with the instructions in the guide. I'll monitor the issue above and see if it gets resolved. If the uberlab guide needs to be adjusted, I can do that later.

**Comment by stephanmaus** [comment]
Hi! Unfortunately, the guide is still broken. Tried to install Friendica on a fresh uberspace but the frontend doesn't load and I get the message "500 Internal Server Error". All the best!

**Comment by rickgardner077** [comment]
I just tried it again following the guide to clone and install Friendica 2022.05-rc, following a request from the Friendica devs. Did not work, same error.

**Comment by toddy15** [comment]
@rickgardner077 Did you change the PHP version to 8.1 or did you use the default 7.4?

**Comment by rickgardner077** [comment]
I tried again installing on a fresh uberspace with PHP 8.1 and this time it worked. Apparently PHP version needs to be 8.1. Will walk through the installation and let you know how it went

**Comment by rickgardner077** [comment]
The guide should be changed to PHP 8.1.

Both stable and 2022.05-rc work with PHP 8.1.

**Comment by toddy15** [comment]
Thanks for your confirmation, this is my finding as well. I've already submitted a PR for this: #1266
