### ISSUE TITLE
[mobilizon] Planned guide after successful installation

### ISSUE THREAD

**Issue by moan0s** [Uberspace/lab#1288]
There are two viable installation strategies for Mobilizon

**[Installation via Release](https://docs.joinmobilizon.org/administration/install/release/)** and **[via source](https://docs.joinmobilizon.org/administration/install/source/)**

Both ways of installation have to be adapted to uberspace and currently present problems. In the following I will decribe them and the easier way will land in the lab

# Release

After downloading the release a configuration file should be created in [this step](https://docs.joinmobilizon.org/administration/install/release/#configuration)

Running the adjusted command fails due to a missing dependency
```
[isabell@stardust mobilizon]$ ./bin/mobilizon_ctl instance gen --output config.exs --output-psql setup_db.psql
/home/isabell/mobilizon/erts-12.3.1/bin/beam.smp: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```
Can a user easily install `ncurses` to solve this?

# Source

The installation via source fails when using [yarn run build](https://docs.joinmobilizon.org/administration/install/source/#installing-dependencies)

We suspect that uberspace automatically kills the process as it uses to much resources.

``` bash
[isabell@stardust js]$ NODE_BUILD_MEMORY=512 yarn run build
yarn run v1.22.19
$ yarn run build:assets && yarn run build:pictures
$ vue-cli-service build --report
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠸  Building for production.../home/isabell/mobilizon/js/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:19
        closedError = new RpcIpcMessagePortClosedError_1.RpcIpcMessagePortClosedError(code
                      ^

RpcIpcMessagePortClosedError: Process 14669 exited [SIGKILL].
    at /home/isabell/mobilizon/js/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:19:23
    at Generator.next (<anonymous>)
    at /home/isabell/mobilizon/js/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/isabell/mobilizon/js/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:4:12)
    at ChildProcess.handleExit (/home/isabell/mobilizon/js/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:18:42)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: null,
  signal: 'SIGKILL'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[isabell@stardust js]$
```

Any help in solving these issues is appreciated :)

**Comment by moan0s** [comment]
Maybe related to the build from source error: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/674

**Comment by xJohnDoe993** [comment]
ive found following in the umami guide:

> In newer versions, sometimes the build process fails without any errors in the next build stage. This is due to Uberspace killing the process for needing to much memory. If this happens, you will not be able to start the app – it will say Error: Could not find a production build in the ‘/home/isabell/umami/.next […]’ directory. Try running the build process via NODE_OPTIONS=--max_old_space_size=512 npm run build --debug to limit the RAM usage and build the app successfully.


Which still leads to following result

> NODE_OPTIONS=--max_old_space_size=512 npm run build --debug
> 
> > mobilizon@3.1.1 build
> > yarn run build:assets && yarn run build:pictures
> 
> yarn run v1.22.19
> $ vite build
> vite v4.3.9 building for production...
> transforming (558) node_modules/@apollo/client/utilities/common/objects.js
> ../../../img/pics/event_creation-480w.webp referenced in /home/johndoe1/mobilizon/js/src/views/Event/MyEventsView.vue?vue&type=style&index=0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime
> 
> ../../../img/pics/event_creation-1024w.webp referenced in /home/johndoe1/mobilizon/js/src/views/Event/MyEventsView.vue?vue&type=style&index=0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime
> 
> ../../../img/pics/group-480w.webp referenced in /home/johndoe1/mobilizon/js/src/views/Group/MyGroups.vue?vue&type=style&index=0&scoped=cdeb967c&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime
> 
> ../../../img/pics/group-1024w.webp referenced in /home/johndoe1/mobilizon/js/src/views/Group/MyGroups.vue?vue&type=style&index=0&scoped=cdeb967c&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime
> transforming (1072) node_modules/@sentry/vue/esm/router.js
> <--- Last few GCs --->
> 
> [3210:0x60d3be0]    36105 ms: Mark-sweep (reduce) 506.1 (520.9) -> 505.5 (521.4) MB, 616.9 / 0.0 ms  (average mu = 0.144, current mu = 0.083) allocation failure; scavenge might not succeed
> [3210:0x60d3be0]    36809 ms: Mark-sweep (reduce) 506.6 (521.4) -> 501.9 (521.4) MB, 681.6 / 0.0 ms  (average mu = 0.091, current mu = 0.032) task; scavenge might not succeed
> 
> 
> <--- JS stacktrace --->
> 
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
>  1: 0xb8dd80 node::Abort() [/opt/nodejs18/bin/node]
>  2: 0xa94c2d  [/opt/nodejs18/bin/node]
>  3: 0xd76850 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/nodejs18/bin/node]
>  4: 0xd76b2a v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/nodejs18/bin/node]
>  5: 0xf61a35  [/opt/nodejs18/bin/node]
>  6: 0xf62934 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/opt/nodejs18/bin/node]
>  7: 0xf73373 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/opt/nodejs18/bin/node]
>  8: 0xf73fb0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/nodejs18/bin/node]
>  9: 0xf4cef7 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/nodejs18/bin/node]
> 10: 0xf4e1a8 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/nodejs18/bin/node]
> 11: 0xf2c679 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/opt/nodejs18/bin/node]
> 12: 0x13410e6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/opt/nodejs18/bin/node]
> 13: 0x17b88b9  [/opt/nodejs18/bin/node]
> error Command failed with signal "SIGABRT".
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

but maybe thats a bit more information which could help debugging.

**Comment by tburny** [comment]
I would really love to try Mobilizon on Uberspace to organize events for my community. Any help here would be highly appreciated.

**Comment by xJohnDoe993** [comment]
@tburny you can also try [Gancio](https://lab.uberspace.de/guide_gancio/) may it meet your requirements.
I didnt try the build process for later versions of Mobilizon on Uberspace but i guess it still doesnt work.
