### ISSUE TITLE
[directus] glib 2.25 required - fix in guide not working

### ISSUE THREAD

**Issue by s-kestler** [Uberspace/lab#1338]
I successfully installed directus a while ago (version 9.12 I think). Now with version 9.19 your guide seems to no longer work. When updating or installing directus 9.19 the stated solution for glib 2.17 vs. glib 2.25 is no longer possible, because the rebuild command throws errors. Any idea on how to fix that?

Here is the output:

`$ npx node-pre-gyp rebuild -C ./node_modules/argon2`
`node-pre-gyp info it worked if it ends with ok`
`node-pre-gyp info using node-pre-gyp@1.0.10`
`node-pre-gyp info using node@16.18.0 | linux | x64`
`node-pre-gyp info chdir ./node_modules/argon2`
`[argon2] Removing "/home/USER/directus/node_modules/argon2/lib/binding/napi-v3"`
`gyp info it worked if it ends with ok`
`gyp info using node-gyp@9.1.0`
`gyp info using node@16.18.0 | linux | x64`
`gyp info ok `
`gyp info it worked if it ends with ok`
`gyp info using node-gyp@9.1.0`
`gyp info using node@16.18.0 | linux | x64`
`gyp WARN chdir ./node_modules/argon2 is not a directory`
`gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"`
`gyp http GET https://nodejs.org/download/release/v16.18.0/node-v16.18.0-headers.tar.gz`
`gyp http 200 https://nodejs.org/download/release/v16.18.0/node-v16.18.0-headers.tar.gz`
`gyp http GET https://nodejs.org/download/release/v16.18.0/SHASUMS256.txt`
`gyp http 200 https://nodejs.org/download/release/v16.18.0/SHASUMS256.txt`
`gyp info spawn /usr/bin/python3`
`gyp info spawn args [`
`gyp info spawn args   '/home/USER/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',`
`gyp info spawn args   'binding.gyp',`
`gyp info spawn args   '-f',`
`gyp info spawn args   'make',`
`gyp info spawn args   '-I',`
`gyp info spawn args   '/home/USER/directus/node_modules/argon2/build/config.gypi',`
`gyp info spawn args   '-I',`
`gyp info spawn args   '/home/USER/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',`
`gyp info spawn args   '-I',`
`gyp info spawn args   '/home/USER/.cache/node-gyp/16.18.0/include/node/common.gypi',`
`gyp info spawn args   '-Dlibrary=shared_library',`
`gyp info spawn args   '-Dvisibility=default',`
`gyp info spawn args   '-Dnode_root_dir=/home/USER/.cache/node-gyp/16.18.0',`
`gyp info spawn args   '-Dnode_gyp_dir=/home/USER/lib/node_modules/npm/node_modules/node-gyp',`
`gyp info spawn args   '-Dnode_lib_file=/home/USER/.cache/node-gyp/16.18.0/<(target_arch)/node.lib',`
`gyp info spawn args   '-Dmodule_root_dir=/home/USER/directus/node_modules/argon2',`
`gyp info spawn args   '-Dnode_engine=v8',`
`gyp info spawn args   '--depth=.',`
`gyp info spawn args   '--no-parallel',`
`gyp info spawn args   '--generator-output',`
`gyp info spawn args   'build',`
`gyp info spawn args   '-Goutput_dir=.'`
`gyp info spawn args ]`
`gyp info ok `
`gyp info it worked if it ends with ok`
`gyp info using node-gyp@9.1.0`
`gyp info using node@16.18.0 | linux | x64`
`gyp WARN chdir ./node_modules/argon2 is not a directory`
`gyp info spawn make`
`gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]`
`make: Entering directory '/home/USER/directus/node_modules/argon2/build'`
`  CC(target) Release/obj.target/libargon2/argon2/src/opt.o`
`  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o`
`  CC(target) Release/obj.target/libargon2/argon2/src/core.o`
`  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o`
`  CC(target) Release/obj.target/libargon2/argon2/src/thread.o`
`  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o`
`  AR(target) Release/obj.target/argon2.a`
`  COPY Release/argon2.a`
`  SOLINK_MODULE(target) Release/obj.target/argon2.node`
`g++: error: Release/obj.target/argon2/argon2.o: No such file or directory`
`make: *** [argon2.target.mk:155: Release/obj.target/argon2.node] Error 1`
`make: Leaving directory '/home/USER/directus/node_modules/argon2/build'`
`gyp ERR! build error `
`gyp ERR! stack Error: `make` failed with exit code: 2`
`gyp ERR! stack     at ChildProcess.onExit (/home/USER/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)`
`gyp ERR! stack     at ChildProcess.emit (node:events:513:28)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)`
`gyp ERR! System Linux 3.10.0-1160.62.1.el7.x86_64`
`gyp ERR! command "/opt/nodejs16/bin/node" "/home/USER/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--directory=./node_modules/argon2" "--module=/home/USER/directus/node_modules/argon2/lib/binding/napi-v3/argon2.node" "--module_name=argon2" "--module_path=/home/USER/directus/node_modules/argon2/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"`
`gyp ERR! cwd /home/USER/directus/node_modules/argon2`
`gyp ERR! node -v v16.18.0`
`gyp ERR! node-gyp -v v9.1.0`
`gyp ERR! not ok `
`node-pre-gyp ERR! build error `
`node-pre-gyp ERR! stack Error: Failed to execute '/opt/nodejs16/bin/node /home/USER/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --directory=./node_modules/argon2 --module=/home/USER/directus/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/home/USER/directus/node_modules/argon2/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)`
`node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/USER/directus/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)`
`node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)`
`node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)`
`node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`
`node-pre-gyp ERR! System Linux 3.10.0-1160.62.1.el7.x86_64`
`node-pre-gyp ERR! command "/opt/nodejs16/bin/node" "/home/USER/directus/node_modules/.bin/node-pre-gyp" "rebuild" "-C" "./node_modules/argon2"`
`node-pre-gyp ERR! cwd /home/USER/directus/node_modules/argon2`
`node-pre-gyp ERR! node -v v16.18.0`
`node-pre-gyp ERR! node-pre-gyp -v v1.0.10`
`node-pre-gyp ERR! not ok `
`Failed to execute '/opt/nodejs16/bin/node /home/USER/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --directory=./node_modules/argon2 --module=/home/USER/directus/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/home/USER/directus/node_modules/argon2/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)`

**Comment by beardcoder** [comment]
A Workaround is to use the version 0.2x not 0.3x
Downgrade and rebuild from source. 
`npm install @mapbox/node-pre-gyp argon2@0.29 && npx node-pre-gyp rebuild -C ./node_modules/argon2`

**Comment by s-kestler** [comment]
Thank you for your answer! The downgrade and build worked - but still no directus. Maybe I am just to dumb but I still get errors and can't start directus. 
Here's the error during directus init:

```
$ npx directus init
node:internal/modules/cjs/loader:1239
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/USER/directus/node_modules/directus/node_modules/argon2/lib/binding/napi-v3/argon2.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1239:18)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/USER/directus/node_modules/directus/node_modules/argon2/argon2.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by beardcoder** [comment]
I have the same problem. since directus ships the new argon2.

the workaroud is
`cd node_modules/directus && npm install argon2@0.29 && npx node-pre-gyp rebuild -C ./node_modules/argon2 && cd ../../`

**Comment by s-kestler** [comment]
That worked! Thank you so much! 

Grüße von Oberbayern nach Niederbayern ;-)
