### ISSUE TITLE
[mailman3] guide is broken

### ISSUE THREAD

**Issue by kimdiallo** [Uberspace/lab#1553]
@rikroe  After following all the steps, the mailman3 service cannot be started because the system openssl version is too low.

```bash
 File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self.context.end()
  File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/config.py", line 701, in end
    self.stack.pop().finish()
  File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/config.py", line 868, in finish
    args = toargs(context, *self.argdata)
  File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/config.py", line 1698, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/fields.py", line 272, in fromUnicode
    v = vt.fromUnicode(s)
  File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/fields.py", line 174, in fromUnicode
    value = self.context.resolve(name)
  File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/config.py", line 223, in resolve
    __import__(mname)
  File "/home/isabell/.local/lib/python3.8/site-packages/mailman/model/autorespond.py", line 28, in <module>
    from mailman.utilities.datetime import today
  File "/home/isabell/.local/lib/python3.8/site-packages/mailman/utilities/datetime.py", line 27, in <module>
    from mailman.testing import layers
  File "/home/isabell/.local/lib/python3.8/site-packages/mailman/testing/layers.py", line 43, in <module>
    from mailman.testing.helpers import (
  File "/home/isabell/.local/lib/python3.8/site-packages/mailman/testing/helpers.py", line 47, in <module>
    from requests import request
  File "/home/isabell/.local/lib/python3.8/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/isabell/.local/lib/python3.8/site-packages/urllib3/__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./.local/bin/master", line 11, in <module>
    load_entry_point('mailman==3.3.8', 'console_scripts', 'master')()
  File "/home/isabell/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/isabell/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/isabell/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/isabell/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/isabell/.local/lib/python3.8/site-packages/mailman/bin/master.py", line 576, in main
    initialize(config_file, verbose)
  File "/home/isabell/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 228, in initialize
    initialize_1(config_path)
  File "/home/isabell/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 104, in initialize_1
    xmlconfig.string(read_text('mailman.config', 'configure.zcml'))
  File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 678, in string
    processxmlfile(f, context)
  File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 409, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib64/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/builds/uberspace/packages/python3.8/Python-3.7.16/Modules/pyexpat.c", line 469, in EndElement
  File "/usr/lib64/python3.8/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 395, in endElementNS
    self._handle_exception(ex, info)
  File "/home/isabell/.local/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 237, in _handle_exception
    raise ZopeXMLConfigurationError(info, ex)
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "<string>", line 19.2-23.6
    ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
```

**Comment by eojjn** [comment]
@rikroe that seems to have sorted the urllib3 problem....now there's another

**Comment by eojjn** [comment]
`Traceback (most recent call last):
  File "/home/$USER/.local/bin/master", line 33, in <module>
    sys.exit(load_entry_point('mailman==3.3.8', 'console_scripts', 'master')())
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/bin/master.py", line 576, in main
    initialize(config_file, verbose)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 229, in initialize
    initialize_2(propagate_logs=propagate_logs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 198, in initialize_2
    initialize_pipelines()
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/pipelines.py", line 73, in initialize
    add_components('handlers', IHandler, config.handlers)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 218, in add_components
    for component_class in find_pluggable_components(subpackage, interface):
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 177, in find_pluggable_components
    yield from find_components('mailman.' + subpackage, interface)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 150, in find_components
    module = import_module(module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/handlers/arc_sign.py", line 22, in <module>
    from authheaders import sign_message
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/__init__.py", line 25, in <module>
    from authheaders.dmarc_lookup import dns_query, receiver_record, receiver_record_walk, get_org_domain
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/dmarc_lookup.py", line 22, in <module>
    from pkg_resources import resource_filename  # Part of setuptools
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flufl.i18n>=3.2' distribution was not found and is required by mailman
Traceback (most recent call last):
  File "/home/$USER/.local/bin/master", line 33, in <module>
    sys.exit(load_entry_point('mailman==3.3.8', 'console_scripts', 'master')())
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/bin/master.py", line 576, in main
    initialize(config_file, verbose)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 229, in initialize
    initialize_2(propagate_logs=propagate_logs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 198, in initialize_2
    initialize_pipelines()
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/pipelines.py", line 73, in initialize
    add_components('handlers', IHandler, config.handlers)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 218, in add_components
    for component_class in find_pluggable_components(subpackage, interface):
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 177, in find_pluggable_components
    yield from find_components('mailman.' + subpackage, interface)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 150, in find_components
    module = import_module(module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/handlers/arc_sign.py", line 22, in <module>
    from authheaders import sign_message
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/__init__.py", line 25, in <module>
    from authheaders.dmarc_lookup import dns_query, receiver_record, receiver_record_walk, get_org_domain
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/dmarc_lookup.py", line 22, in <module>
    from pkg_resources import resource_filename  # Part of setuptools
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flufl.i18n>=3.2' distribution was not found and is required by mailman
Traceback (most recent call last):
  File "/home/$USER/.local/bin/master", line 33, in <module>
    sys.exit(load_entry_point('mailman==3.3.8', 'console_scripts', 'master')())
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/bin/master.py", line 576, in main
    initialize(config_file, verbose)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 229, in initialize
    initialize_2(propagate_logs=propagate_logs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 198, in initialize_2
    initialize_pipelines()
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/pipelines.py", line 73, in initialize
    add_components('handlers', IHandler, config.handlers)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 218, in add_components
    for component_class in find_pluggable_components(subpackage, interface):
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 177, in find_pluggable_components
    yield from find_components('mailman.' + subpackage, interface)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 150, in find_components
    module = import_module(module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/handlers/arc_sign.py", line 22, in <module>
    from authheaders import sign_message
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/__init__.py", line 25, in <module>
    from authheaders.dmarc_lookup import dns_query, receiver_record, receiver_record_walk, get_org_domain
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/dmarc_lookup.py", line 22, in <module>
    from pkg_resources import resource_filename  # Part of setuptools
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flufl.i18n>=3.2' distribution was not found and is required by mailman
Traceback (most recent call last):
  File "/home/$USER/.local/bin/master", line 33, in <module>
    sys.exit(load_entry_point('mailman==3.3.8', 'console_scripts', 'master')())
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/bin/master.py", line 576, in main
    initialize(config_file, verbose)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 229, in initialize
    initialize_2(propagate_logs=propagate_logs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 198, in initialize_2
    initialize_pipelines()
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/pipelines.py", line 73, in initialize
    add_components('handlers', IHandler, config.handlers)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 218, in add_components
    for component_class in find_pluggable_components(subpackage, interface):
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 177, in find_pluggable_components
    yield from find_components('mailman.' + subpackage, interface)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 150, in find_components
    module = import_module(module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/handlers/arc_sign.py", line 22, in <module>
    from authheaders import sign_message
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/__init__.py", line 25, in <module>
    from authheaders.dmarc_lookup import dns_query, receiver_record, receiver_record_walk, get_org_domain
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/dmarc_lookup.py", line 22, in <module>
    from pkg_resources import resource_filename  # Part of setuptools
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flufl.i18n>=3.2' distribution was not found and is required by mailman
`

**Comment by eojjn** [comment]
I think I've got mailman3 working now.
Changed "startsecs=30" to "startsecs=0" in ~/etc/services.d/mailman3.ini

**Comment by eojjn** [comment]
`pip3.8 install --upgrade setuptools`
using this command meant that the error has now changed from containing 
> /usr/lib/python3.8/site-packages/[...]

to containing 

> /home/$USER/.local/lib/python3.8/site-packages/[...]

I'm not really sure what to make of this. The changes to setuptools were actually only made to the user environment as far as I saw...

New error: 

> Traceback (most recent call last):
  File "/home/$USER/.local/bin/master", line 33, in <module>
    sys.exit(load_entry_point('mailman==3.3.8', 'console_scripts', 'master')())
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/bin/master.py", line 576, in main
    initialize(config_file, verbose)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 229, in initialize
    initialize_2(propagate_logs=propagate_logs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 198, in initialize_2
    initialize_pipelines()
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/pipelines.py", line 73, in initialize
    add_components('handlers', IHandler, config.handlers)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 218, in add_components
    for component_class in find_pluggable_components(subpackage, interface):
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 177, in find_pluggable_components
    yield from find_components('mailman.' + subpackage, interface)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 150, in find_components
    module = import_module(module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/handlers/arc_sign.py", line 22, in <module>
    from authheaders import sign_message
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/__init__.py", line 25, in <module>
    from authheaders.dmarc_lookup import dns_query, receiver_record, receiver_record_walk, get_org_domain
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/dmarc_lookup.py", line 22, in <module>
    from pkg_resources import resource_filename  # Part of setuptools
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3327, in <module>
    def _initialize_master_working_set():
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3301, in _call_aside
    f(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3339, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 629, in _build_master
    ws.require(__requires__)
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 868, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flufl.i18n>=3.2' distribution was not found and is required by mailman
Traceback (most recent call last):
  File "/home/$USER/.local/bin/master", line 33, in <module>
    sys.exit(load_entry_point('mailman==3.3.8', 'console_scripts', 'master')())
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/$USER/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/bin/master.py", line 576, in main
    initialize(config_file, verbose)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 229, in initialize
    initialize_2(propagate_logs=propagate_logs)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/initialize.py", line 198, in initialize_2
    initialize_pipelines()
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/core/pipelines.py", line 73, in initialize
    add_components('handlers', IHandler, config.handlers)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 218, in add_components
    for component_class in find_pluggable_components(subpackage, interface):
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 177, in find_pluggable_components
    yield from find_components('mailman.' + subpackage, interface)
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/utilities/modules.py", line 150, in find_components
    module = import_module(module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/$USER/.local/lib/python3.8/site-packages/mailman/handlers/arc_sign.py", line 22, in <module>
    from authheaders import sign_message
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/__init__.py", line 25, in <module>
    from authheaders.dmarc_lookup import dns_query, receiver_record, receiver_record_walk, get_org_domain
  File "/home/$USER/.local/lib/python3.8/site-packages/authheaders/dmarc_lookup.py", line 22, in <module>
    from pkg_resources import resource_filename  # Part of setuptools
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3327, in <module>
    def _initialize_master_working_set():
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3301, in _call_aside
    f(*args, **kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3339, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 629, in _build_master
    ws.require(__requires__)
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
  File "/home/$USER/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 868, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flufl.i18n>=3.2' distribution was not found and is required by mailman

**Comment by eojjn** [comment]
I seem to have now fixed the issue by downgrading flufl.i18n to 3.2

**Comment by dakni** [comment]
I had the same issue and solved it by installing an older version of `urllib3`:

```
pip3.8 install --user urllib3==1.26.6
```

After that, everything worked as explained in the guide.

**Comment by noave** [comment]
Ok looks like there is currently several issues with dependencies in mailman:

https://gitlab.com/mailman/mailman/-/issues/1085

The original problem here was on side of Uberspace, that the urllib3 cannot work with the serveside openssl version, pinning an old version fixes this:

```
$ pip3.8 install "urllib3<2"
```
Because of the `importlib_resource` problem, as proposed in the issue: https://gitlab.com/mailman/mailman/-/issues/1093 we will use an older version of this lib as well:
```
$ pip3.8 install "importlib_resources<6.0"
```
And because of the (not investigated to the end) `flufl` lib issues (see https://gitlab.com/mailman/mailman/-/issues/1085) it worked for me to just pin a lower version as well:
```
$ pip3.8 install "flufl.lock<8"
$ pip3.8 install "flufl.i18n<5"
```

with those downgrades, a fresh installation ist working for me. I would be happy ia another user can confirm this when installing mailman3.
