### ISSUE TITLE
Add a guide for puppeteer

### ISSUE THREAD

**Issue by Snapstromegon** [Uberspace/lab#604]
[Puppeteer](https://github.com/puppeteer/puppeteer) is a project from Google to enable browser testing using node and the Chrome Browser.

I have a working version running on a space and am willing to contribute a guide for this if it's wanted.

At the moment you'd need to "install" some libraries (see [here](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix)), because they don't already exist on uberspace.

This can be done by using a combination of yumdownloader, rpm2cpio and cpio (and setting the LD_LIBRARY_PATH environment variable).

**Comment by rumgewieselt** [comment]
Hi @Snapstromegon, i tryed today to install puppeteer without success. Maybe you have a small how to do? This would be great. Thanks.

**Comment by Snapstromegon** [comment]
Hey, I will write you a short list later today, but I didn't end up using it because of the sandbox problem.

**Comment by Snapstromegon** [comment]
I'll make this fairly short - please tell me if you have any problem:
```
1. ~$ mkdir puppeteer
2. ~$ cd puppeteer
3. puppeteer$ mkdir rpms
4. puppeteer$ cd rpms
# download librarys
5. rpms$ yumdownloader alsa-lib atk cups-libs GConf2 gtk3 ipa-gothic-fonts libXcomposite libXcursor libXdamage libXext libXi libXrandr libXScrnSaver libXtst pango xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-fonts-cyrillic xorg-x11-fonts-misc xorg-x11-fonts-Type1 xorg-x11-utils at-spi2-atk cairo-gobject libepoxy libxkbcommon libwayland-cursor libwayland-egl --resolve
6. rpms$ cd ..
# extract libarys
7. puppeteer$ for f in rpms/*.rpm; do rpm2cpio $f | cpio -idm ;done
# delete rpms
8. puppeteer$ rm -rf rpms
9. puppeteer$ nano ~/.bashrc
#insert the following
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/puppeteer/lib:$HOME/puppeteer/lib64:$HOME/puppeteer/usr/lib:$HOME/puppeter/usr/lib64

10. source ~/.bashrc
```

Now you can npm install puppeteer and use it (pass the --no-sandbox argument).

**Be aware that this is a non sandboxed version of chromium so it's more dangerous to run unknown code!**

Example which worked on my side:
```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({args: ["--no-sandbox"]})
  const page = await browser.newPage()
  await page.setViewport({ width: 1280, height: 800 })
  await page.goto('https://www.nytimes.com/')
  await page.screenshot({ path: 'nytimes.png', fullPage: true })
  await browser.close()
})()
```

**Comment by rumgewieselt** [comment]
Thanks for the short list. 

I get these error if i try your example.js:

node example.js
(node:6608) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/speed/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: wrong ELF class: ELFCLASS32


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/speed/node_modules/puppeteer/lib/Launcher.js:547:20)
    at Interface.<anonymous> (/home/speed/node_modules/puppeteer/lib/Launcher.js:537:65)
    at Interface.emit (events.js:333:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:6608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Maybe i have something wrong? Thanks a lot.

**Comment by Snapstromegon** [comment]
Okay, the error message says that it found a 32bit Binary of the library libXss.so.1.
I updated my comment in two ways to help with those problems:

1. I added --archlist=x86_64 to step 5, but since uberspace runs 64bit CentOS7 I don't expect that this changes much.

2. More importantly I changed the order of the folders in the LD_LIBRARY_PATH so the 64 bit versions get searched first. That way your problem should be solved.

**Comment by rumgewieselt** [comment]
After changing the order of LD_LIBRARY_PATH it works. Perfect. Thanks a lot for your help!
