### ISSUE TITLE
[Rockaet.Chat] rocket.chat: ERROR (spawn error) after update

### ISSUE THREAD

**Issue by GITchristoph** [Uberspace/lab#865]
Hi

Ich habe versucht auf 3.9.1 zu aktualisieren.

Nach npm install kommen nur Fehlermeldungen.

Vielleicht bin ich ja nicht der einzige.
Ich bin so ein wenig am Ende meiner Debugfähiglkeiten hier :-)

Das Ende des logs sieht so aus:

```
3625 verbose stack Error: fibers@3.1.1 install: `node build.js || nodejs build.js`
3625 verbose stack spawn ENOENT
3625 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs12/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
3625 verbose stack     at ChildProcess.emit (events.js:314:20)
3625 verbose stack     at maybeClose (internal/child_process.js:1021:16)
3625 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
3626 verbose pkgid fibers@3.1.1
3627 verbose cwd /home/xxx/rocket.chat/programs/server
3628 verbose Linux 3.10.0-1127.19.1.el7.x86_64
3629 verbose argv "/opt/nodejs12/bin/node" "/opt/nodejs12/bin/npm" "install"
3630 verbose node v12.19.0
3631 verbose npm  v6.14.8
3632 error code ELIFECYCLE
3633 error syscall spawn
3634 error file sh
3635 error errno ENOENT
3636 error fibers@3.1.1 install: `node build.js || nodejs build.js`
3636 error spawn ENOENT
3637 error Failed at the fibers@3.1.1 install script.
3637 error This is probably not a problem with npm. There is likely additional logging output above.
3638 verbose exit [ 1, true ]
```

Die letzten Meldungen nach "npm install" gibt das aus:

```
10424 | void ReturnValue<T>::Set(const Persistent<S>& handle) {
      |      ^~~~~~~~~~~~~~
make: *** [fibers.target.mk:120: Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/home/xyz/rocket.chat/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs12/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-1127.19.1.el7.x86_64
gyp ERR! command "/opt/nodejs12/bin/node" "/opt/nodejs12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/xxx/rocket.chat/programs/server/node_modules/fibers
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! fibers@3.1.1 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@3.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2020-12-08T08_42_29_498Z-debug.log
```

**Comment by GITchristoph** [comment]
I also tried to install 3.8.3 again but always the same issue.

```
[xxx@arche server]$ npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN lifecycle The node binary used for scripts is /usr/bin/node but npm is using /opt/nodejs12/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> fibers@3.1.1 install /home/yna/rocket.chat/programs/server/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory '/home/yna/rocket.chat/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
```

**Comment by GITchristoph** [comment]
I tried

**Comment by sauberfred** [comment]
It looks like some of the downloaded archives are corrupted: [https://github.com/RocketChat/Rocket.Chat/issues/19795#issuecomment-740622681](https://github.com/RocketChat/Rocket.Chat/issues/19795#issuecomment-740622681)

I just installed version 3.9.1 successfully!

**Comment by GITchristoph** [comment]
Basically I start installing and then it gives continiously error messages. Not sure what this is.

```
npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN lifecycle The node binary used for scripts is /usr/bin/node but npm is using /opt/nodejs12/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> fibers@3.1.1 install /home/xx/rocket.chat/programs/server/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory '/home/xx/rocket.chat/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:68:2: error: ‘Handle’ does not name a type
   68 |  Handle<String> NewLatin1String(Isolate* isolate, const char* string) {
      |  ^~~~~~
../src/fibers.cc:72:2: error: ‘Handle’ does not name a type
   72 |  Handle<String> NewLatin1Symbol(Isolate* isolate, const char* string) {
      |  ^~~~~~
../src/fibers.cc:94:2: error: ‘Handle’ does not name a type
   94 |  Handle<Object> NewInstance(Isolate* isolate, Local<Function> fn, int argc, Local<Value> argv[]) {
      |  ^~~~~~
../src/fibers.cc:104:2: error: ‘Handle’ does not name a type
  104 |  Handle<Number> ToNumber(Local<Value> value) {
      |  ^~~~~~
../src/fibers.cc:114:50: error: ‘Handle’ has not been declared
  114 |  Local<Value> GetStackTrace(TryCatch* try_catch, Handle<Context> context) {
      |                                                  ^~~~~~
../src/fibers.cc:114:56: error: expected ‘,’ or ‘...’ before ‘<’ token
```
  114 |  Local<Value> GetStackTrace(TryCatch* try_catch, Handle<Context> context) {
      |                                                        ^
../src/fibers.cc: In function ‘v8::Local<v8::Value> uni::GetStackTrace(uni::TryCatch*, int)’:
../src/fibers.cc:115:32: error: ‘context’ was not declared in this scope; did you mean ‘ucontext’?
  115 |   return try_catch->StackTrace(context).ToLocalChecked();
      |                                ^~~~~~~
      |                                ucontext
../src/fibers.cc: At global scope:
../src/fibers.cc:127:39: error: ‘Handle’ has not been declared
  127 |  void fixStackLimit(Isolate* isolate, Handle<Context> context) {
      |                                       ^~~~~~
../src/fibers.cc:127:45: error: expected ‘,’ or ‘...’ before ‘<’ token
  127 |  void fixStackLimit(Isolate* isolate, Handle<Context> context) {
      |                                             ^
../src/fibers.cc: In function ‘void uni::fixStackLimit(v8::Isolate*, int)’:
../src/fibers.cc:128:19: error: ‘context’ was not declared in this scope; did you mean ‘ucontext’?
  128 |   Script::Compile(context, uni::NewLatin1String(isolate, "void 0;")).ToLocalChecked();
      |                   ^~~~~~~
      |                   ucontext
../src/fibers.cc:128:33: error: ‘NewLatin1String’ is not a member of ‘uni’
  128 |   Script::Compile(context, uni::NewLatin1String(isolate, "void 0;")).ToLocalChecked();
      |                                 ^~~~~~~~~~~~~~~

**Comment by GITchristoph** [comment]
> It looks like some of the downloaded archives are corrupted: [RocketChat/Rocket.Chat#19795 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/19795#issuecomment-740622681)
> 
> I just installed version 3.9.1 successfully, using the direct link.


Sorry, havent' seen this yet. Willl try that!

**Comment by GITchristoph** [comment]
> It looks like some of the downloaded archives are corrupted: [RocketChat/Rocket.Chat#19795 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/19795#issuecomment-740622681)
> 
> I just installed version 3.9.1 successfully, using the direct link.

Thank you - That was it. Sorry to disturb ...
